# Generated by Django 4.2.1 on 2024-01-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="history",
            field=models.TextField(blank=True),
        ),
    ]
